# docker-compose.yml

services:
  django:
    build:
      context: ./APIService/  # Path to your Django Dockerfile
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./APIService:/app  # Mount your Django code into the container
    ports:
      - "8000:8000"     # Expose Django on port 8000
    env_file:
      - ./APIService/.env  
    depends_on:
      - nextjs

  nextjs:
    build:
      context: ./chart-dashboard-ui  # Path to your Next.js Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"      # Expose Next.js on port 3000
    env_file:
      - ./chart-dashboard-ui/.env 
